// examples/shuttle-port-vue/src/components/ArbitrarySign.vue
<script lang="ts" setup>
import { Buffer } from 'buffer'
import { ref } from 'vue'
import { useShuttle } from '@delphi-labs/shuttle-vue'

import useWallet from '@/composables/useWallet'

const shuttle = useShuttle()
const wallet = useWallet()

const data = ref('')

function onSign() {
  const bytes = Buffer.from(data.value, 'utf-8')
  shuttle
    .signArbitrary({
      wallet: wallet.value,
      data: bytes
    })
    .then(async (result) => {
      console.log('sign arbitrary result', result)

      console.group('###### verifying signature.... ########')
      const verification = await shuttle.verifyArbitrary({
        wallet: wallet.value,
        data: bytes,
        signResult: result
      })
      console.log('verification result:', verification)
      console.log('####################################')
      console.groupEnd()
    })
    .catch((error) => {
      console.error('sign arbitrary error', error)
    })
}
</script>

<template>
  <h2>Sign arbitrary</h2>
  <textarea v-model="data" :style="{ width: '450px', height: '100px' }" />
  <button @click="() => onSign()">Sign</button>
</template>

// examples/shuttle-port-nextjs/src/components/ArbitrarySign.tsx
"use client";

import { useState } from "react";
import { useShuttle } from "@delphi-labs/shuttle-react";

import useWallet from "@/hooks/useWallet";

export function ArbitrarySign() {
  const { signArbitrary, verifyArbitrary } = useShuttle();
  const wallet = useWallet();

  const [data, setData] = useState("");

  const onSign = () => {
    const bytes = Buffer.from(data, "utf-8");
    signArbitrary({
      wallet,
      data: bytes,
    })
      .then(async (result) => {
        console.log("sign arbitrary result", result);

        console.group("###### verifying signature.... ########");
        const verification = await verifyArbitrary({
          wallet,
          data: bytes,
          signResult: result,
        });
        console.log("verification result:", verification);
        console.log("####################################");
        console.groupEnd();
      })
      .catch((error) => {
        console.error("sign arbitrary error", error);
      });
  };

  return (
    <>
      <h2>Sign arbitrary</h2>
      <textarea value={data} onChange={(e) => setData(e.target.value)} style={{ width: "450px", height: "100px" }} />
      <button onClick={onSign}>Sign</button>
    </>
  );
}
