// examples/shuttle-port-vue/src/components/EthereumSign.vue
<script lang="ts" setup>
import { ref } from "vue";
import { EthSignType } from "@delphi-labs/shuttle";
import { useShuttle } from "@delphi-labs/shuttle-vue";

import useWallet from "@/composables/useWallet";

const shuttle = useShuttle();
const wallet = useWallet();

const data = ref("");

function onSign() {
  shuttle
    .signEthereum({
      wallet: wallet.value,
      data: data.value,
      type: EthSignType.MESSAGE,
    })
    .then(async (result) => {
      console.log("sign ethereum result", result);
    })
    .catch((error) => {
      console.error("sign ethereum error", error);
    });
}
</script>

<template>
  <h2>Sign Ethereum</h2>
  <textarea v-model="data" :style="{ width: '450px', height: '100px' }" />
  <button @click="() => onSign()">Sign</button>
</template>

// examples/shuttle-port-nextjs/src/components/EthereumSign.tsx
"use client";

import { useState } from "react";
import { EthSignType, useShuttle } from "@delphi-labs/shuttle-react";

import useWallet from "@/hooks/useWallet";

export function EthereumSign() {
  const { signEthereum } = useShuttle();
  const wallet = useWallet();

  const [data, setData] = useState("");

  const onSign = () => {
    signEthereum({
      wallet,
      data: data,
      type: EthSignType.MESSAGE,
    })
      .then(async (result) => {
        console.log("sign ethereum result", result);
      })
      .catch((error) => {
        console.error("sign ethereum error", error);
      });
  };

  return (
    <>
      <h2>Sign Ethereum</h2>
      <textarea value={data} onChange={(e) => setData(e.target.value)} style={{ width: "450px", height: "100px" }} />
      <button onClick={onSign}>Sign</button>
    </>
  );
}
